name: 'Pluralsight Demo: Get Employee Slack Action'
description: "Looks up an employee's Slack ID by their GitHub username"
inputs:
  github-token:
    description: 'The GitHub token to authenticate with GitHub API'
    required: true
    default: '${{ secrets.GITHUB_TOKEN }}'
  github-username:
    description: 'The GitHub username of the employee to look up'
    required: true
    default: '${{ github.actor }}'
  slack-token:
    description: 'The organizational Slack access token'
    required: true
    default: '${{ secrets.SLACK_TOKEN }}'
outputs:
  slack-user-id:
    description: 'The Slack user ID of the employee, if found'
runs:
  using: 'node20'
  main: main.js